### ISSUE TITLE
git hook question

### ISSUE THREAD

**Issue by jkozdon** [lcw/Harpy.jl#1]
https://github.com/lcw/Harpy.jl/blob/04b87b95123eba5b640a1a63f95f34711d86ef5a/misc/git/hooks/pre-commit#L10

Is there a reason not to do:
```
JLFILES=$(git diff --name-only --cached HEAD | grep '.*\.jl$')
```

**Comment by lcw** [comment]
If I remember correctly, it is because `--cached` includes the files that are being deleted.  This can cause issues when looping over the entries in `$JLFILES` as some of them do not exist.

**Comment by jkozdon** [comment]
Ah. Makes sense.
